### ISSUE TITLE
remove jquery dependency and remove findLocationAddress()

### ISSUE THREAD

**Issue by tomwayson** [Esri/ember-arcgis-portal-services#147]
We only use jquery to deep merge the inputs to `findLocationAddress()`:

https://github.com/Esri/ember-arcgis-portal-services/blob/c1bc54c6dadf5d40aa3bb2a964463b8a0fdd74a8/addon/services/geocode-service.js#L2

We [don't use that fn in the Hub](https://github.com/ArcGIS/opendata-ui/search?q=findLocationAddress&unscoped_q=findLocationAddress), and it's arguably out of the scope of this repo. If it were to stay in this repo, we should update it to use [@esri/arcgis-rest-geocoder](https://www.npmjs.com/package/@esri/arcgis-rest-geocoder), which is what we're using directly in the Hub.

I think it would be easier to remove `findLocationAddress()` and bump major than to do all that^^^.

**Comment by jgravois** [comment]
done in #153
