### ISSUE TITLE
Remove ember-ajax dependency

### ISSUE THREAD

**Issue by tomwayson** [Esri/ember-arcgis-portal-services#32]
No longer in use

**Comment by jgravois** [comment]
resolved via ae2085771831406f8be610ea0869202be6bc230d

**Comment by tomwayson** [comment]
Except we should probably now use [ember-fetch](https://github.com/ember-cli/ember-fetch) - just sayin'

**Comment by tomwayson** [comment]
Oops, we already do.

Ignore me. Sorry.
