### ISSUE TITLE
Calling items service method when not signed in, code hits syntax error and promise isn't resolved/rejected

### ISSUE THREAD

**Issue by skitterm** [Esri/ember-arcgis-portal-services#80]
The README mentions that most methods take in an optional `portalOpts` property. However, calling `this.get('itemsService').getDataById(appId)` when not signed in (i.e. incognito browser), passing no `portalOpts` parameter, the code hits an error and no request to the item is made. And the error gets swallowed (there's no log in the console of the error, even when I do a `.catch` on that promise), and the promise is never resolved/rejected.

[Here](https://github.com/Esri/ember-arcgis-portal-services/blob/master/addon/mixins/service-mixin.js#L38) is where it errors. Error is `cannot read property "replace" of undefined`.

Happy to provide code snippet if needed.

**Comment by tomwayson** [comment]
Thanks @skitterm. I assume your use case is accessing a public item on ArcGIS Online. That is something this addon should not only support, but also be clear about how to do. I think that if you supply a `portalOpts` w/ `portalHostname` it _should_ work. 

However, I wonder if a better way of supporting this use case would be to assume this public ArcGIS Online use case if no `session` or `portalOpts` is supplied. It's just not a scenario that we have (all of our apps use [torii-provider-arcgis](https://github.com/dbouwman/torii-provider-arcgis/)), so we haven't put much thought to it.

**Comment by jgravois** [comment]
better late than never, but this is resolved in `v1.5.1` (by virtue of #113)

![screenshot 2018-08-17 12 45 32](https://user-images.githubusercontent.com/3011734/44285774-8c82d000-a21b-11e8-8b4f-ce1ef7b29126.png)
