### ISSUE TITLE
Stringify serviceProxyParams

### ISSUE THREAD

**Issue by skitterm** [Esri/ember-arcgis-portal-services#86]
It'd be great if `serviceProxyParams` (http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r30000008q000000) was JSON-stringified like `properties` is. We stringify the `serviceProxyParams` property in some of our apps before saving (creating or updating an item), and it'd be awesome to have EAPS take care of this for us.

**Comment by jgravois** [comment]
this one is resolved too.

![screenshot 2018-08-17 14 11 45](https://user-images.githubusercontent.com/3011734/44289059-7d098400-a227-11e8-947d-bc8365105770.png)


hat trick!
