### ISSUE TITLE
start running tests in Travis

### ISSUE THREAD

**Issue by tomwayson** [Esri/ember-arcgis-portal-services#94]
We'll probably have to either switch tests to FF, not use sandbox, or use `sudo: required` https://github.com/Esri/ember-arcgis-portal-services/pull/93/files/193e47bd14e179be35dc21d9a8ac650e0c0c608c#diff-354f30a63fb0907d4ad57269548329e3R6

**Comment by jgravois** [comment]
i pinged the github admins to try and get admin access to enable travis, but so far, 🏏 s.

**Comment by tomwayson** [comment]
Thanks John! We're gonna need this for all the other add-ons too. Don't know if it helps or hurts to batch those.

Get Outlook for Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_ghei36&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=Fug_L2S2jeLu6S8kOuWhjrkDqgsJjV2_gUxNyWLfkDiF4nqxcVo8IIwhq2swqlQL5bFRunDZA0MPMThlHHw9_ftpTpwqWs5xKqV27RfwAHfREqf87uzEb2P18RuVHh7joqoinTdzynqYx5kotR9Fhg&m=r2Zp9yF7d6rnOnOXxYC91yamh4P6u9fp_fOLxlWxz7E&s=9DuKWo4pdPQsFr8zcsA3KHS0ea1ZbehLHdX6RJz8_uo&e=>




On Wed, Jan 24, 2018 at 11:47 AM -0800, "john gravois" <notifications@github.com<mailto:notifications@github.com>> wrote:


i pinged the github admins to try and get admin access to enable travis, but so far, 🏏 s.

**Comment by jgravois** [comment]
the fact that i made a request for **all** our repos definitely slowed down _this_ request, but in the long run, the housekeeping was long overdue and and will streamline this kind of thing in the future.
